services:
  mousesearch:
    image: sevenlayercookie/mousesearch:latest
    container_name: mousesearch
    ports:
      - "5009:5000"
    env_file: .env
    volumes:
      - ./data:/app/data
      - /mnt/sda/audiobooks:/audiobooks/
      # - /mnt/sda/audiobooks/docker/qbittorrent/downloads/prowlarr:/qbittorrent
      # - /mnt/sda/organized:/organized
    restart: unless-stopped
    networks:
      - proxy-network
      - default
networks:
  proxy-network:
    external: true
